"""Export reviewed 512px player attacks; never ship provisional spear paintings.

Usage: python tools/player-attacks.py <authoring-package> <game-checkout>
"""
import hashlib
import json
import shutil
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parents[1]
source, game = map(Path, sys.argv[1:3])
manifest = json.loads((source / 'manifest.json').read_text())
review = json.loads((source / 'qa/visual-review.json').read_text())
approved = {s['actionId'] for s in review['sequences'] if s['result'] == 'visually-reviewed-candidate'}
archive = root / 'art/player-attacks-2026-10-09'
archive.mkdir(parents=True, exist_ok=True)
for name in ['manifest.json', 'README.txt', 'qa/visual-review.json', 'qa/file-validation.json']:
    target = archive / name
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source / name, target)
catalog = {}
def export_frame(job):
    seq, frame = job
    target = root / f"hd/assets/animations/player-attacks/{seq['character']}/{seq['weaponFamily']}/{frame['phase']}.webp"
    target.parent.mkdir(parents=True, exist_ok=True)
    if '--resume' in sys.argv and target.exists() and target.stat().st_size:
        with Image.open(target) as existing:
            existing.verify()
        return
    with Image.open(source / frame['path']) as original:
        original.convert('RGBA').save(target, 'WEBP', quality=90, method=6, exact=True)

jobs = [(seq, frame) for seq in manifest['sequences'] if seq['actionId'] in approved for frame in seq['frames']]
with ThreadPoolExecutor(max_workers=4) as pool:
    list(pool.map(export_frame, jobs))
for seq in manifest['sequences']:
    if seq['actionId'] not in approved:
        continue
    frames = {}
    poses = []
    for frame in seq['frames']:
        original = source / frame['path']
        retained = archive / frame['path']
        retained.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(original, retained)
        provenance = frame.get('provenance', {}).get('path')
        if provenance and (source / provenance).is_file():
            retained_source = archive / provenance
            retained_source.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source / provenance, retained_source)
        image = Image.open(original).convert('RGBA')
        asset = f"assets/animations/player-attacks/{seq['character']}/{seq['weaponFamily']}/{frame['phase']}.webp"
        target = root / 'hd' / asset
        target.parent.mkdir(parents=True, exist_ok=True)
        pose = seq['actionId'] + '.' + frame['phase']
        poses.append(pose)
        frames[pose] = {'path': asset, 'bounds': list(image.getchannel('A').getbbox()), 'sha256': hashlib.sha256(target.read_bytes()).hexdigest()}
    catalog.setdefault(seq['character'], {})[seq['weaponFamily']] = {
        'frames': frames,
        'sequence': {'poses': poses, 'durations': [f['durationMs'] for f in seq['frames']], 'impact': 1, 'travel': [0, 0, 0, 0], 'hold': False},
    }
for path in (source / 'source').glob('*.json'):
    (archive / 'source').mkdir(exist_ok=True)
    shutil.copy2(path, archive / 'source' / path.name)
shutil.copytree(source / 'references', archive / 'references', dirs_exist_ok=True)
(game / 'src/content/playerAttackSprites.js').write_text('// Generated by AshenSpire-art tools/player-attacks.py; reviewed default outfits only.\nexport const playerAttackSprites = ' + json.dumps(catalog, separators=(',', ':')) + ';\n')
print(f'Exported {sum(map(len, catalog.values()))} reviewed sequences')
