"""Export the selected counter/sweep package into isolated art/game checkouts."""
import hashlib
import json
import shutil
import sys
from pathlib import Path
from PIL import Image

source, art, game = map(Path, sys.argv[1:4])
selected = source / 'options/selected' if (source / 'options/selected').is_dir() else source
manifest = json.loads((selected / 'manifest.json').read_text(encoding='utf-8'))
base_text = (game / 'src/content/alternativeCardAnimations.js').read_text(encoding='utf-8')
base = json.loads(base_text.split('export const alternativeCardAnimations = ')[1].strip().removesuffix(';'))
archive = art / 'art/player-counter-sweep-2026-10-09'
archive.mkdir(parents=True, exist_ok=True)
def copy_file(src, dst):
    if src.resolve() != dst.resolve():
        shutil.copy2(src, dst)
for name in ['favorites.json', 'manifest.json', 'manifest.js', 'index.html', 'preview.js', 'README.md']:
    copy_file(selected / name, archive / name)
for folder in ['effects', 'projects', 'qa']:
    if selected.resolve() != archive.resolve():
        shutil.copytree(selected / folder, archive / folder, dirs_exist_ok=True)
copy_file(selected / 'chooser.css' if (selected / 'chooser.css').exists() else source / 'options/chooser.css', archive / 'chooser.css')
html = (archive / 'index.html').read_text(encoding='utf-8').replace('../chooser.css', 'chooser.css')
html = html.replace('<a href="../">All 40 options</a>', '')
(archive / 'index.html').write_text(html, encoding='utf-8', newline='\n')
catalog = {}
for clip in manifest['clips']:
    actor, action = clip['actor'], clip['action']
    entry = catalog.setdefault(actor, {'frames': {}, 'effects': {}, 'sequences': {}, 'stances': {}})
    ready_bounds = base['classes'][actor]['frames']['ready']['bounds']
    idle = Image.open(selected / clip['frames'][-1]['file']).convert('RGBA')
    idle_bounds = idle.getchannel('A').getbbox()
    factor = (464 - ready_bounds[1]) / (464 - idle_bounds[1])
    poses, effects = [], []
    def export(original, name, collection):
        image = Image.open(original).convert('RGBA')
        # All body/effect layers share one affine registration around the floor.
        image = image.transform((512, 512), Image.Transform.AFFINE,
            (1/factor, 0, 256-256/factor, 0, 1/factor, 464-464/factor), Image.Resampling.BICUBIC)
        bounds = list(image.getchannel('A').getbbox())
        asset = f'assets/animations/player-counter-sweep/{actor}/{action}/{name}.webp'
        output = art / 'hd' / asset
        output.parent.mkdir(parents=True, exist_ok=True)
        image.resize((256, 256), Image.Resampling.LANCZOS).save(output, 'WEBP', quality=90, method=6, exact=True)
        key = f'{actor}.{action}.{name}'
        collection[key] = {'path': asset, 'bounds': bounds, 'anchor': [256, 464],
            'rasterSize': [256, 256], 'sha256': hashlib.sha256(output.read_bytes()).hexdigest()}
        return key
    for i, frame in enumerate(clip['frames']):
        retained = archive / 'clips' / clip['id'] / f'{i}.png'
        retained.parent.mkdir(parents=True, exist_ok=True)
        copy_file(selected / frame['file'], retained)
        frame['file'] = retained.relative_to(archive).as_posix()
        poses.append(export(retained, ['stance', 'contact', 'recovery'][i], entry['frames']) if i < 3 else 'ready')
        effects.append(export(selected / frame['effect'], f'effect-{i}', entry['effects']) if frame['effect'] else None)
    entry['stances'][action] = poses[0]
    entry['sequences'][action] = {'selection': clip['id'], 'label': clip['label'], 'poses': poses,
        'durations': [f['duration'] for f in clip['frames']], 'impact': 1,
        'travel': [0, 0, 0, 0], 'effects': effects, 'hold': False}
    clip['runtimeRegistration'] = {'scale': factor, 'anchor': [256, 464], 'finalPose': 'existing ready'}
manifest['scope'] = 'Owner-selected source package; runtime returns to the original ready frame.'
(archive / 'manifest.json').write_text(json.dumps(manifest, indent=2)+'\n', encoding='utf-8', newline='\n')
(archive / 'manifest.js').write_text('window.SELECTED_CLIPS='+json.dumps(manifest)+';\n', encoding='utf-8', newline='\n')
(game / 'src/content/playerCounterSweepSprites.js').write_text(
    '// Generated by AshenSpire-art tools/player-counter-sweep.py; owner selections, separate effects.\n'
    'export const playerCounterSweepSprites = '+json.dumps(catalog, separators=(',', ':'))+';\n', encoding='utf-8', newline='\n')
copy_file(Path(__file__), art / 'tools/player-counter-sweep.py')
print('Exported eight selected sequences, 24 body frames and 16 independent effects.')
